services:
  mlflow-server:
    build:
      context: mlflow/
    container_name: mlflow
    ports:
      - "5001:5000"
    networks:
      - transformer-mlflow
    volumes:
    - mlflow_data:/mlflow
  
  training:
    build: .
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
    volumes:
      - ./data:/app/data
    depends_on:
      - mlflow-server
    networks:
      - transformer-mlflow

volumes:
  mlflow_data:

networks:
  transformer-mlflow:
    